name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: 'Features'
    labels:
      - feature
      - enhancement

  - title: 'Fixes'
    labels:
      - bug
      - fix

  - title: 'Performance'
    labels:
      - performance

  - title: 'Documentation'
    labels:
      - docs
      - documentation

  - title: 'Maintenance'
    labels:
      - chore
      - refactor
      - deps
      - ci

change-template: '- $TITLE (#$NUMBER)'

exclude-labels:
  - skip-changelog

template: |
  ## Changes
  $CHANGES
